In [24]:
import numpy as np
import pandas as pd

# Number of samples per class
n_samples = 1000
n_class_0 = int(n_samples * 0.9)
n_class_1 = n_samples - n_class_0

# Create DataFrames for each class
class_0_df = pd.DataFrame({
    'feature1': np.random.normal(0, 1, n_class_0),
    'feature2': np.random.normal(0, 1, n_class_0),
    'target': [0] * n_class_0
})

class_1_df = pd.DataFrame({
    'feature1': np.random.normal(2, 1, n_class_1),
    'feature2': np.random.normal(2, 1, n_class_1),
    'target': [1] * n_class_1
})

In [26]:
class_0_df

     feature1  feature2  target
0   -1.085631  0.551302       0
1    0.997345  0.419589       0
2    0.282978  1.815652       0
3   -1.506295 -0.252750       0
4   -0.578600 -0.292004       0
..        ...       ...     ...
895  0.238761 -0.003155       0
896 -1.106386 -0.430660       0
897  0.366732 -0.146416       0
898  1.023906  1.160176       0
899 -0.210056 -0.641512       0

[900 rows x 3 columns]

In [27]:
class_1_df

    feature1  feature2  target
0   1.699768  2.139033       1
1   1.367739  2.025577       1
2   1.795683  1.803557       1
3   2.213696  3.312255       1
4   3.033878  3.187417       1
..       ...       ...     ...
95  1.376371  2.845701       1
96  2.239810  0.880077       1
97  1.131760  1.640703       1
98  2.902006  0.390305       1
99  2.697490  2.013570       1

[100 rows x 3 columns]

In [28]:
# Combine into a single dataset
data = pd.concat([class_0_df, class_1_df], ignore_index=True)

In [29]:
data

     feature1  feature2  target
0   -1.085631  0.551302       0
1    0.997345  0.419589       0
2    0.282978  1.815652       0
3   -1.506295 -0.252750       0
4   -0.578600 -0.292004       0
..        ...       ...     ...
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

[1000 rows x 3 columns]

In [30]:
from sklearn.utils import resample

# Separate majority and minority
class_0_data = data[data['target'] == 0]
class_1_data = data[data['target'] == 1]

# Oversample minority class to match majority
class_1_oversampled = resample(class_1_data, 
                               replace=True,       # sample with replacement
                               n_samples=len(class_0_data), # match majority
                               random_state=123)

# Combine back into balanced dataset
balanced_data = pd.concat([class_0_data, class_1_oversampled], ignore_index=True)

# Shuffle the dataset
balanced_data = balanced_data.sample(frac=1, random_state=123).reset_index(drop=True)

# Check counts
print(balanced_data['target'].value_counts())

target
0    900
1    900
Name: count, dtype: int64

In [31]:
# Separate majority and minority
class_0_data = data[data['target'] == 0]
class_1_data = data[data['target'] == 1]

# Downsample majority class to match minority
class_0_downsampled = resample(class_0_data,
                               replace=False,      # no replacement, just pick a subset
                               n_samples=len(class_1_data),  # match minority size
                               random_state=123)

# Combine downsampled majority with minority class
balanced_data = pd.concat([class_0_downsampled, class_1_data], ignore_index=True)

# Shuffle the dataset
balanced_data = balanced_data.sample(frac=1, random_state=123).reset_index(drop=True)

# Check counts
print(balanced_data['target'].value_counts())

target
0    100
1    100
Name: count, dtype: int64